name = "contextmax"
compatibility_date = "2025-06-13"
pages_build_output_dir = "dist"

[build]
command = "npm run generate"

[build.environment_variables]
NODE_VERSION = "18"

[env.production]
name = "contextmax-curator"

[env.preview]
name = "contextmax-curator-preview"
