name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Clean install dependencies
        run: |
          # Remove node_modules and package-lock to ensure clean state
          rm -rf node_modules package-lock.json
          # Install without ignoring scripts so all binaries are properly installed
          npm install
          # Prepare Nuxt
          npx nuxi prepare || true
      
      - name: Run tests
        run: npm test
      
      - name: Update version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        id: version-bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          NEW_VERSION=$(npm version ${{ github.event.inputs.version }} -m "chore: bump version to %s" | sed 's/^v//')
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git push origin HEAD:${{ github.ref_name }}
      
      - name: Generate static files
        run: npm run generate
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Create GitHub Release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.version-bump.outputs.version }} \
            --title "Release v${{ steps.version-bump.outputs.version }}" \
            --notes "Release v${{ steps.version-bump.outputs.version }}" \
            --draft=false