name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Clean install dependencies
        run: |
          # Remove node_modules and package-lock to ensure clean state
          rm -rf node_modules package-lock.json
          # Install without ignoring scripts so all binaries are properly installed
          npm install
          # Prepare Nuxt
          npx nuxi prepare || true
      
      - name: Run tests
        run: npm test
      
      - name: Update version from release tag
        run: |
          RELEASE_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          npm version $RELEASE_VERSION --no-git-tag-version
      
      - name: Generate static files
        run: npm run generate
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}